(in-package #:cl-user)

(defpackage #:standard.collection
  (:nicknames #:std.collection #:collection)
  (:use #:cl #:std.base)
  (:shadowing-import-from #:std.base #:coerce)
  (:shadow
   #:get
   #:copy
   #:length
   #:position
   #:position-if
   #:count
   #:count-if
   #:reduce
   #:find
   #:find-if
   #:remove
   #:map
   #:remove-if
   #:remove-duplicates
   #:reverse
   #:fill
   #:substitute
   #:substitute-if
   #:append
   #:sort
   #:stable-sort
   #:merge)
  (:export
   #:get
   #:put!
   #:copy
   #:copy^
   #:length
   #:position
   #:position-if
   #:copy
   #:remove
   #:remove^
   #:map-to
   #:map
   #:split
   #:split-if
   #:count
   #:count-if
   #:reduce
   #:find
   #:find-if
   #:remove-if
   #:remove-if^
   #:filter
   #:filter^
   #:remove-duplicates
   #:remove-duplicates^
   #:reverse
   #:reverse^
   #:fill
   #:substitute
   #:substitute!
   #:substitute-if
   #:substitute-if!
   #:append
   #:append!
   #:sort
   #:sort^
   #:stable-sort
   #:stable-sort^
   #:merge
   #:merge^))